In [1]:
import pandas as pd

In [2]:
def get_mta_data(dates):
    file_path_string = 'http://web.mta.info/developers/data/nyct/turnstile/turnstile_{}.txt'
    dfs = []
    for date in dates:
        df = pd.read_csv(file_path_string.format(date))
        dfs.append(df)
    return pd.concat(dfs)

In [3]:
df = get_mta_data(['200627', '200620'])
#Kaggle Data Sets
nyc_census_tracts = pd.read_csv('./data/nyc_census_tracts.csv')
census_block_loc = pd.read_csv('./data/census_block_loc.csv')
# Stations with Census Block ids and Census Tract ids
stations = pd.read_csv('./data/stations.csv')

In [4]:
stations.head()

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,Census Block,Census Tract
0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034,NaN,Manhattan,360810115002001,36081011500
1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843,Ditmars Blvd,Manhattan,360810125001009,36081012500
2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479,Astoria - Ditmars Blvd,Manhattan,360810063001001,36081006300
3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508,Astoria - Ditmars Blvd,Manhattan,360810059003000,36081005900
4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575,Astoria - Ditmars Blvd,Manhattan,360810053004002,36081005300

In [5]:
stations_with_census = pd.merge(stations,
                                nyc_census_tracts[['CensusTract', 'Poverty']],
                                left_on='Census Tract', 
                                right_on='CensusTract')

In [6]:
stations_with_census.sort_values('Poverty', ascending=False).head(10)

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,Census Block,Census Tract,CensusTract,Poverty
10,158,158,A20,IND,8th Av - Fulton St,86 St,M,B C,Subway,40.785868,-73.968916,Uptown & The Bronx,Downtown & Brooklyn,360610143001015,36061014300,36061014300,100.0
8,8,8,R13,BMT,Astoria,5 Av/59 St,M,N W R,Subway,40.764811,-73.973347,Queens,Downtown & Brooklyn,360610143001051,36061014300,36061014300,100.0
9,157,157,A19,IND,8th Av - Fulton St,96 St,M,B C,Subway,40.791642,-73.964696,Uptown & The Bronx,Downtown & Brooklyn,360610143001014,36061014300,36061014300,100.0
11,159,159,A21,IND,8th Av - Fulton St,81 St - Museum of Natural History,M,B C,Subway,40.781433,-73.972143,Uptown & The Bronx,Downtown & Brooklyn,360610143001029,36061014300,36061014300,100.0
12,160,160,A22,IND,8th Av - Fulton St,72 St,M,B C,Subway,40.775594,-73.976410,Uptown & The Bronx,Downtown & Brooklyn,360610143001038,36061014300,36061014300,100.0
167,349,349,254,IRT,Eastern Pky,Junius St,Bk,3,Elevated,40.663515,-73.902447,Manhattan,New Lots,360470910003000,36047091000,36047091000,67.3
166,135,135,L26,BMT,Canarsie,Livonia Av,Bk,L,Elevated,40.664038,-73.900571,Manhattan,Canarsie - Rockaway Parkway,360470910004004,36047091000,36047091000,67.3
165,134,134,L25,BMT,Canarsie,Sutter Av,Bk,L,Elevated,40.669367,-73.901975,Manhattan,Canarsie - Rockaway Parkway,360470908002000,36047090800,36047090800,62.1
196,163,611,A27,IND,8th Av - Fulton St,42 St - Port Authority Bus Terminal,M,A C E,Subway,40.757308,-73.989735,Uptown - Queens,Downtown & Brooklyn,360610119002005,36061011900,36061011900,55.5
197,468,611,902,IRT,Lexington - Shuttle,Times Sq - 42 St,M,S,Subway,40.755983,-73.986229,NaN,Grand Central,360610119001005,36061011900,36061011900,55.5

In [7]:
stations.columns

Index(['Station ID', 'Complex ID', 'GTFS Stop ID', 'Division', 'Line',
       'Stop Name', 'Borough', 'Daytime Routes', 'Structure', 'GTFS Latitude',
       'GTFS Longitude', 'North Direction Label', 'South Direction Label',
       'Census Block', 'Census Tract'],
      dtype='object')